import { SearchResultItem, QuickActionItem } from './types';

export const MOCK_SEARCH_ITEMS: SearchResultItem[] = [
  // Pages
  {
    id: 'page-overview',
    title: 'Overview',
    subtitle: 'Executive pulse, attention items, top metrics',
    group: 'Pages',
    targetNav: 'overview',
  },
  {
    id: 'page-finance',
    title: 'Finance',
    subtitle: 'Runway, burn rate, live bank ledger & disbursements',
    group: 'Pages',
    targetNav: 'finance',
    department: 'finance',
  },
  {
    id: 'page-hiring',
    title: 'Hiring',
    subtitle: 'Talent pipeline, candidates, scorecard loops',
    group: 'Pages',
    targetNav: 'hiring',
    department: 'hiring',
  },
  {
    id: 'page-legal',
    title: 'Legal',
    subtitle: 'Contracts, NDAs, Delaware compliance, corporate vault',
    group: 'Pages',
    targetNav: 'legal',
    department: 'legal',
  },
  {
    id: 'page-marketing',
    title: 'Marketing',
    subtitle: 'Launch campaigns, announcements, press releases',
    group: 'Pages',
    targetNav: 'marketing',
    department: 'marketing',
  },
  {
    id: 'page-approvals',
    title: 'Approvals',
    subtitle: 'Human-in-the-loop decision queue & audit log',
    group: 'Pages',
    targetNav: 'approvals',
    badge: '3 Pending',
  },
  {
    id: 'page-calendar',
    title: 'Calendar',
    subtitle: 'Important deadlines, loops, milestones, launch dates',
    group: 'Pages',
    targetNav: 'calendar',
  },
  {
    id: 'page-activity',
    title: 'Activity',
    subtitle: 'Live chronological audit log across all agents',
    group: 'Pages',
    targetNav: 'activity',
  },
  {
    id: 'page-profile',
    title: 'Profile',
    subtitle: 'Founder identity & startup information',
    group: 'Pages',
    targetNav: 'profile',
  },
  {
    id: 'page-settings',
    title: 'Settings',
    subtitle: 'Workspace preferences, notifications, security',
    group: 'Pages',
    targetNav: 'settings',
  },

  // Documents
  {
    id: 'doc-nda-monochrome',
    title: 'Mutual Non-Disclosure Agreement · Studio Monochrome',
    subtitle: 'Bilateral Delaware NDA with contractor IP assignment',
    group: 'Documents',
    targetNav: 'approvals',
    department: 'legal',
    badge: 'Ready for Review',
  },
  {
    id: 'doc-nda-foundry',
    title: 'Series Seed Mutual NDA · Foundry Group',
    subtitle: 'Diligence room mutual confidentiality agreement',
    group: 'Documents',
    targetNav: 'legal',
    department: 'legal',
    badge: 'Executed',
  },
  {
    id: 'doc-contractor-msa',
    title: 'Design Systems Lead Contractor Agreement (MSA)',
    subtitle: 'Master services agreement covering Q4 design token sprint',
    group: 'Documents',
    targetNav: 'legal',
    department: 'legal',
  },
  {
    id: 'doc-offer-aisha',
    title: 'Executive Employment Offer · Aisha Khan',
    subtitle: 'Staff Frontend Engineer offer letter & CIIA assignment',
    group: 'Documents',
    targetNav: 'legal',
    department: 'legal',
  },
  {
    id: 'doc-safe-note',
    title: 'Post-Money SAFE Note Agreement ($150K Angel)',
    subtitle: 'Standard YC valuation cap agreement executed',
    group: 'Documents',
    targetNav: 'finance',
    department: 'finance',
  },

  // People
  {
    id: 'person-sarah',
    title: 'Sarah Lin',
    subtitle: 'Founder & CEO · Authorized Signatory',
    group: 'People',
    targetNav: 'profile',
    badge: 'Owner',
  },
  {
    id: 'person-theo',
    title: 'Theo Dumas',
    subtitle: 'Candidate · Staff UI Engineer (Top score: 98/100)',
    group: 'People',
    targetNav: 'hiring',
    department: 'hiring',
    badge: 'Shortlisted',
  },
  {
    id: 'person-aisha',
    title: 'Aisha Khan',
    subtitle: 'Candidate · Staff Frontend Engineer (Interview Loop Complete)',
    group: 'People',
    targetNav: 'hiring',
    department: 'hiring',
    badge: 'Offer Ready',
  },
  {
    id: 'person-elena',
    title: 'Elena Rostova',
    subtitle: 'Candidate · Systems Frontend Engineer (Score: 94/100)',
    group: 'People',
    targetNav: 'hiring',
    department: 'hiring',
  },
  {
    id: 'person-marcus',
    title: 'Marcus Chen',
    subtitle: 'Candidate · Web Performance Engineer (Score: 91/100)',
    group: 'People',
    targetNav: 'hiring',
    department: 'hiring',
  },

  // Campaigns
  {
    id: 'camp-v12-launch',
    title: 'FORGE OS v1.2 GA Product Launch',
    subtitle: 'Public announcement staged for Substack, X, & Press Wires',
    group: 'Campaigns',
    targetNav: 'marketing',
    department: 'marketing',
    badge: 'Oct 28 Embargo',
  },
  {
    id: 'camp-linkedin',
    title: 'Product Launch — LinkedIn announcement',
    subtitle: 'Founder release brief and thought leadership post',
    group: 'Campaigns',
    targetNav: 'approvals',
    department: 'marketing',
    badge: 'Ready for Review',
  },
  {
    id: 'camp-ph-checklist',
    title: 'Product Hunt Launch Checklist & Assets',
    subtitle: 'Typography cards, GIF demos, and maker comment draft',
    group: 'Campaigns',
    targetNav: 'marketing',
    department: 'marketing',
  },

  // Activities
  {
    id: 'act-runway-update',
    title: 'Financial snapshot updated — 14.8 mo runway',
    subtitle: 'Bank feeds reconciled with Stripe and SVB accounts',
    group: 'Activities',
    targetNav: 'activity',
    department: 'finance',
  },
  {
    id: 'act-nda-drafted',
    title: 'NDA drafted for Studio Monochrome designer',
    subtitle: 'Prepared by FORGE Legal Guard with 0 deviations',
    group: 'Activities',
    targetNav: 'activity',
    department: 'legal',
  },
  {
    id: 'act-candidate-shortlist',
    title: 'Candidate shortlist generated (3 finalists)',
    subtitle: '42 applications filtered by FORGE Talent Engine',
    group: 'Activities',
    targetNav: 'activity',
    department: 'hiring',
  },
];

export const MOCK_QUICK_ACTIONS: QuickActionItem[] = [
  { id: 'qa-finance', label: 'Open Finance', category: 'Core Operations', targetNav: 'finance', shortcut: 'G F' },
  { id: 'qa-hiring', label: 'Open Hiring', category: 'Core Operations', targetNav: 'hiring', shortcut: 'G H' },
  { id: 'qa-legal', label: 'Open Legal', category: 'Core Operations', targetNav: 'legal', shortcut: 'G L' },
  { id: 'qa-marketing', label: 'Open Marketing', category: 'Core Operations', targetNav: 'marketing', shortcut: 'G M' },
  { id: 'qa-approvals', label: 'View Approvals', category: 'Workflow', targetNav: 'approvals', shortcut: 'G A' },
  { id: 'qa-calendar', label: 'Open Calendar', category: 'Workflow', targetNav: 'calendar', shortcut: 'G C' },
  { id: 'qa-activity', label: 'View Activity', category: 'Workflow', targetNav: 'activity', shortcut: 'G V' },
  { id: 'qa-profile', label: 'Founder Profile', category: 'Account', targetNav: 'profile', shortcut: '⌘ P' },
  { id: 'qa-settings', label: 'Open Settings', category: 'Account', targetNav: 'settings', shortcut: '⌘ S' },
];

export const SUGGESTED_COMMANDS: string[] = [
  'Draft an NDA for our new designer',
  'Show me our current runway',
  'Find candidates for Senior Frontend Engineer',
  'Prepare a product launch announcement',
  'Show pending approvals',
];
